name: Every Minute Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: "* * * * *"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "This runs every minute"