on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: idjorgon/hello-barsoom@0.0.7
        with:
          name: 'Rafael & Ivan'
      - name: Get the output
        run: echo "${{ steps.hello.outputs.greeting }}"
