name: "Workflow Commands"
on: ['push']
jobs:
  my-job: 
    runs-on: ubuntu-latest
    steps:
      - name: "Group Logging"
        run: |
          echo "::group::My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
              steps:
      - name: "Set Env"
        run: |
          echo "MY_VAL=hello" >> $GITHUB_ENV
      - name: "Echo Env"
        run: |
          echo $MY_VAL